//
//  YoURLConst.h
//  YoSDKCoreKit
//
//  Created by Yostar on 2022/2/9.
//

#ifndef YoURLConst_h
#define YoURLConst_h
#import <Foundation/Foundation.h>

//push

///用户登陆后的信息提交接口
FOUNDATION_EXPORT NSString * const PushCommitInfoURL;
///消息推送结果的推送接口
FOUNDATION_EXPORT NSString * const PushCallbackURL;

// 网络请求地址后缀
FOUNDATION_EXPORT NSString * const INITSETURL;
///Token迁移
FOUNDATION_EXPORT NSString * const TokenMigrateURL;
FOUNDATION_EXPORT NSString * const CHECKENVTURL;
///错误码与协议版本号检查
FOUNDATION_EXPORT NSString * const VERSIONCHECKURL;
FOUNDATION_EXPORT NSString * const USERCREATEURL;
FOUNDATION_EXPORT NSString * const USERLOGINURL;
FOUNDATION_EXPORT NSString * const USERDETAILURL;
FOUNDATION_EXPORT NSString * const USERQUICKLOGINURL;
FOUNDATION_EXPORT NSString * const TRANSCODEREQURL;
FOUNDATION_EXPORT NSString * const TRANSCODEVERURL;
FOUNDATION_EXPORT NSString * const FBLOGINURL;
FOUNDATION_EXPORT NSString * const DEVICELISTURL;
FOUNDATION_EXPORT NSString * const REMOVEDEVICEURL;
FOUNDATION_EXPORT NSString * const CheckTextLegalityURL;
FOUNDATION_EXPORT NSString * const AgreementConfirmURL;


/**
 调查问卷
 */
FOUNDATION_EXPORT NSString * const SURVEYURL;
///网络状况上报
FOUNDATION_EXPORT NSString * const NETWORKREPORTURL;
FOUNDATION_EXPORT NSString * const UNLINKURL;
FOUNDATION_EXPORT NSString * const LINKURL;
// facebook new api
FOUNDATION_EXPORT NSString * const FBCREATELOGINURL;
FOUNDATION_EXPORT NSString * const FBRELINKURL;
FOUNDATION_EXPORT NSString * const FBLINKURL;
FOUNDATION_EXPORT NSString * const FBUNLINKURL;
FOUNDATION_EXPORT NSString * const TWLOGINURL;
// twitter new api
FOUNDATION_EXPORT NSString * const TWCREATELOGINURL;
FOUNDATION_EXPORT NSString * const TWRELINKURL;
FOUNDATION_EXPORT NSString * const TWLINKURL;
FOUNDATION_EXPORT NSString * const TWUNLINKURL;
FOUNDATION_EXPORT NSString * const SETFUNCTIONURL;
FOUNDATION_EXPORT NSString * const KMCURL;

FOUNDATION_EXPORT NSString * const SENDCODEURL;
///验证原邮箱验证码，第二步
FOUNDATION_EXPORT NSString * const AuthOriginEamilCodeURL;
///获取原邮箱验证码，第一步
FOUNDATION_EXPORT NSString * const GetOriginEmailCodeURL;
FOUNDATION_EXPORT NSString * const AUTHSUBMITURL;
FOUNDATION_EXPORT NSString * const CREATELOGINURL;
FOUNDATION_EXPORT NSString * const YORELINKURL;
FOUNDATION_EXPORT NSString * const YOLINKURL;
FOUNDATION_EXPORT NSString * const YOUNLINKURL;
FOUNDATION_EXPORT NSString * const YODELETEURL;
FOUNDATION_EXPORT NSString * const YOREBORNURL;

FOUNDATION_EXPORT NSString * const APPLERELINKURL;
FOUNDATION_EXPORT NSString * const APPLECREATELOGINURL;
FOUNDATION_EXPORT NSString * const APPLELINKURL;
FOUNDATION_EXPORT NSString * const APPLEUNLINKURL;

FOUNDATION_EXPORT NSString * const PRODUCTSURL;
FOUNDATION_EXPORT NSString * const CREATEORDERURL;
FOUNDATION_EXPORT NSString * const CONFIRMORDERURL;
FOUNDATION_EXPORT NSString * const ORDERSTATUSURL;
FOUNDATION_EXPORT NSString * const ORDERMETAURL;

FOUNDATION_EXPORT NSString * const AGREEMENTURL;
//用户协议
FOUNDATION_EXPORT NSString * const USERAGREEMENTURL;
FOUNDATION_EXPORT NSString * const ANNOUNCEURL;
FOUNDATION_EXPORT NSString * const CodeURL;
FOUNDATION_EXPORT NSString * const SummitLogURL;

//支付
//添加信用卡
FOUNDATION_EXPORT NSString * const CreditcardAddURL;
//删除信用卡
FOUNDATION_EXPORT NSString * const CreditcardDeleteURL;
//信用卡列表
FOUNDATION_EXPORT NSString * const CreditcardListURL;
///生成网页通行证
FOUNDATION_EXPORT NSString * const GenWebAccountURL;
#endif /* YoURLConst_h */
